/*创建数据库*/
CREATE DATABASE WEB_CHAT;

/*切换数据库*/
USE WEB_CHAT;

/*删除用户信息表*/
DROP TABLE USER_INFO;
/*用户信息表*/
CREATE TABLE USER_INFO(
	ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(255),
    PASS VARCHAR(255),
    CREATE_TIME TIMESTAMP DEFAULT NOW()
)
ENGINE=INNODB DEFAULT CHARSET=UTF8;

/*删除信息表*/
DROP TABLE MESSAGE_INFO;
/*消息记录表*/
CREATE TABLE MESSAGE_INFO(
	ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    USER_ID BIGINT,
    RECEIVE_USER_ID BIGINT,
    MESSAGE VARCHAR(255),
    STATUS INT,
    CREATE_TIME TIMESTAMP DEFAULT NOW()
)
ENGINE=INNODB DEFAULT CHARSET=UTF8;
