/*创建数据库*/
CREATE DATABASE WEB_CHAT;

/*切换数据库*/
USE WEB_CHAT;

/*删除用户信息表*/
DROP TABLE USER_INFO;
/*用户信息表*/
CREATE TABLE USER_INFO(
	ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(255),
    PASS VARCHAR(255),
    CREATE_TIME TIMESTAMP DEFAULT NOW()
)
ENGINE=INNODB DEFAULT CHARSET=UTF8;

/*删除好友关系列表*/
DROP TABLE FRIEND_INFO;
/*好友关系列表*/
CREATE TABLE FRIEND_INFO(
	USER_ID BIGINT,
    FRIEND_USER_ID BIGINT,
    STATUS INT,
    CREATE_TIME TIMESTAMP DEFAULT NOW(),
    PRIMARY KEY(USER_ID, FRIEND_USER_ID)
)
ENGINE=INNODB DEFAULT CHARSET=UTF8;

/*删除会话表*/
DROP TABLE SESSION_INFO;
/*会话信息表*/
CREATE TABLE SESSION_INFO(
	ID BIGINT,
    USER_ID BIGINT,
    LATEST_MESSAGE_ID BIGINT,
    CREATE_TIME TIMESTAMP DEFAULT NOW(),
    PRIMARY KEY(ID, USER_ID)
)
ENGINE=INNODB DEFAULT CHARSET=UTF8;

/*删除信息表*/
DROP TABLE MESSAGE_INFO;
/*消息记录表*/
CREATE TABLE MESSAGE_INFO(
	ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    SESSION_ID BIGINT,
    USER_ID BIGINT,
    RECEIVE_USER_ID BIGINT,
    MESSAGE VARCHAR(255),
    STATUS INT,
    CREATE_TIME TIMESTAMP DEFAULT NOW()
)
ENGINE=INNODB DEFAULT CHARSET=UTF8;
