USE WEB_CHAT;
SELECT * FROM USER_INFO;

DESC MESSAGE_INFO;

SELECT * FROM SESSION_INFO;

SELECT * FROM SESSION_INFO WHERE RELATION_USER_ID = '2_3' OR RELATION_USER_ID = '3_2';

SELECT * FROM MESSAGE_INFO;

SELECT
a.ID AS messageId,
a.MESSAGE AS message,
a.STATUS AS messageStatus,
b.ID AS sendUserId,
b.NAME AS sendUserName,
c.ID AS receiveUserId,
c.NAME AS receiveUserName
FROM MESSAGE_INFO a LEFT JOIN USER_INFO b ON a.USER_ID = b.ID
LEFT JOIN USER_INFO c ON a.RECEIVE_USER_ID = c.ID
WHERE a.USER_ID = 2 OR a.RECEIVE_USER_ID = 2 AND a.STATUS = 1
ORDER BY a.CREATE_TIME DESC LIMIT 1;


SELECT
a.ID AS messageId,
a.MESSAGE AS message,
a.STATUS AS messageStatus,
a.CREATE_TIME AS messageCreateTime,
b.ID AS sendUserId,
b.NAME AS sendUserName,
c.ID AS receiveUserId,
c.NAME AS receiveUserName
FROM MESSAGE_INFO a LEFT JOIN USER_INFO b ON a.USER_ID = b.ID
LEFT JOIN USER_INFO c ON a.RECEIVE_USER_ID = c.ID
WHERE a.USER_ID = 2 OR a.RECEIVE_USER_ID = 2 AND a.STATUS = 1
GROUP BY a.USER_ID, a.RECEIVE_USER_ID
ORDER BY a.CREATE_TIME








