USE WEB_CHAT;

SELECT * FROM USER_INFO;

DESC MESSAGE_INFO;

SELECT * FROM MESSAGE_INFO;

SELECT * FROM SESSION_INFO;

SELECT * FROM MESSAGE_INFO WHERE SESSION_ID = 1 ORDER BY CREATE_TIME;

SELECT * FROM FRIEND_INFO;

/*获取当前用户聊天列表*/

SELECT
a.ID AS sessionId,
c.ID AS otherUserId,
c.NAME AS otherUserName,
d.STATUS AS friendStatus,
e.message AS latestMessage,
e.STATUS AS messageStatus
FROM (SELECT ID, USER_ID FROM SESSION_INFO WHERE USER_ID = 2) a LEFT JOIN SESSION_INFO b ON a.ID = b.ID
LEFT JOIN USER_INFO c ON b.USER_ID = c.ID
LEFT JOIN FRIEND_INFO d ON c.ID = d.FRIEND_USER_ID AND d.USER_ID = 2
LEFT JOIN MESSAGE_INFO e ON a.ID = e.SESSION_ID AND b.LATEST_MESSAGE_ID = e.ID
WHERE b.USER_ID != 2
GROUP BY b.ID;

SELECT
a.ID AS sessionId,
c.ID AS otherUserId,
c.NAME AS otherUserName,
d.MESSAGE,
d.MAX_TIME
FROM (SELECT ID, USER_ID FROM SESSION_INFO WHERE USER_ID = 1) a LEFT JOIN SESSION_INFO b ON a.ID = b.ID
LEFT JOIN USER_INFO c ON b.USER_ID = c.ID
LEFT JOIN (SELECT ID, SESSION_ID, MESSAGE, MAX(CREATE_TIME) AS MAX_TIME FROM MESSAGE_INFO GROUP BY SESSION_ID) d ON a.ID = d.SESSION_ID;

/*根据双方用户ID查询会话*/
SELECT
a.ID AS id,
a.USER_ID AS userId,
a.CREATE_TIME AS createTime
FROM SESSION_INFO a INNER JOIN SESSION_INFO b ON a.ID = b.ID
WHERE a.USER_ID = 3 AND b.USER_ID = 4;

/*消息信息*/
SELECT
a.ID AS messageId,
b.ID AS sendUserId,
b.NAME AS sendUserName,
a.MESSAGE AS message,
a.STATUS AS messageStatus,
a.CREATE_TIME AS messageTime
FROM MESSAGE_INFO a INNER JOIN USER_INFO b ON a.USER_ID = b.ID
WHERE a.STATUS = 1 AND a.SESSION_ID = 1;

/*查询当前用户好友信息*/
SELECT
b.ID AS frinedUserId,
b.NAME AS friendUserName
FROM FRIEND_INFO a INNER JOIN USER_INFO b ON a.FRIEND_USER_ID = b.ID
WHERE a.USER_ID = 1;













