server:
  port: 8080
spring:
  main:
    allow-circular-references: true
  datasource:
    url: jdbc:mysql://localhost:3307/WEB_CHAT?useSSL=true&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true