server:
  port: 8779
spring:
  main:
    allow-circular-references: true
  datasource:
    url: jdbc:mysql://localhost:3306/WEB_CHAT?useSSL=true&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  thymeleaf:
      cache: false
      prefix: classpath:/templates/
      encoding: UTF-8 #编码
      suffix: .html # 模板后缀
  application:
    name: web-chat
  profiles:
    active: dev
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true


